######################################## CONFIGURACION CIRCUIT BREAKER ########################################
resilience4j:
  circuitbreaker:
    configs:
      # "defecto" es el nombre asignado por nosotros a esta configuracion
      defecto:
      # Aca realizamos las configuraciones del circuit breaker
      # Veremos propiedades, similares a los metodos  utilizados en el metodo "defaulCustomizer()" de la clase "RestTemplateConfig"
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        
    # Asignamos la configuracion "defecto" creado en el archivo actual al circuit breaker llamado "productos" ubicado en el metodo "detalle()" de la clase "ItemController"
    instances:  
      productos: # este es el mismo nombre del circuit breaker en el controlador
        base-config: defecto # Este es el nombre creado mas arriba
  # Tiempo máximo de espera(timeout) a 2 segundos. En el fondo "timelimiter" es como "circuitbreaker" ya que tiene su configuracion
  timelimiter:
    configs:
    # "defecto" es el nombre que asignamos aqui, coincide con el de arriba, pero no es necesario que asi sea.
      defecto:
        timeout-duration: 2s
    # Similar a lo configurado mas arriba, asignamos el "defecto" al circuit breaker "productos" del controlador
    instances:
      productos:
        base-config: defecto
# Registramos este proyecto como cliente de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
######################################## CONFIGURACION API GATEWAY ########################################
# El puerto 8090 es usado comúnmente para los API Gateway
# Este puerto también lo tiene Zuul y lo mantendremos asi ya que solo usaremos uno de los dos.
server:
  port: 8090
spring:
  application:
    name: servicio-gateway-server
  cloud:
    gateway:
      routes:
        # Configuracion de la ruta al microservicio "servicio-productos" asignada por el API Gateway
        - id: servicio-productos
        # En el "uri" estariamos indicando la instancia del microservicio, ya que con "lb://" se indica que se esta utilizando balanceo de carga.
        # lb : Palabra reservada que indica que se accedera a este recuerso mediante balanceo de carga 
        # //servicio-productos : Ruta que debe coincidir con el "id" de arriba, aunque con añadiendo doble slash "//"
          uri: lb://servicio-productos
        # Los "predicate" son reglas/condiciones que debe cumplir el request para que funcionen los endpoints configurados en el "application.yml". 
          predicates:
          # Indicamos las rutas, en este caso solo una
          - Path=/api/productos/**
          # Regla para que en el "header" del request, contenga un "token" y su valor sea cualquier valor numerico(\d+)
          ##- Header=token, \d+
          # Regla para que en el "header" del request, tenga un contenido en formato "json". Para get no es recomendable, pero si para post o put
          ##- Header=Content-Type, application/json
          # Regla para solo admitir metodos get y post
          ##- Method=GET, POST
          # Regla para el "param" del request, contenga un key=color y value={cualquiera_en_este_caso}
          ##- Query=color
          # Regla para el "cookie" del request, contenga un key=color y value=azul
          ##- Cookie=color, azul
        # stripPrefix=2 : Filtro necesario ya que el "Path" arriba asignado, esta compuesto por 2 segmentos
        # Estos segmentos(cantidad de palabras dividas por un slash) son "/api" y "/productos/"
          filters:
          # Filtro que representa un circuit breaker
          # "CircuitBreaker" es una palabra reservada de spring cloud gateway
          # "productos" representa el nombre de la instancia del "circuit breaker", asignada arriba en "instances: productos"
          - name: CircuitBreaker
            args:
              name: productos
              statusCodes: 500, 404 # codigos de estado esperados, el 500 corresponde a la excepcion enviada por el servicio de productos con el id 10
              fallbackUri: forward:/api/items/ver/9/cantidad/5 # configuracion de ruta alternativa para cuando ocurra el "circuit breaker"
          - StripPrefix=2
          # Segunda opcion de configurar un "filtro por rutas". El nombre y los parametros separados por comas y espacios.
          # Los "value" de estos "name" los asignaremos en el metodo "shortcutFieldOrder()" de la clase "EjemploGatewayFilterFactory"
          # "EjemploCookie" es el valor retornado en el metodo "name()" de la clase "EjemploGatewayFilterFactory"
          - EjemploCookie=Hola mi mensaje personalizado, usuario
          # Primera opcion utilizando el atributo "name" con el sufijo "...GatewayFilterFactory" en el nombre de la clase.          
          # Configuracion en la ruta de productos, agregando un "filtro por rutas"
          # Este palabra "Ejemplo" corresponde al prefijo del nombre de la clase "EjemploGatewayFilterFactory",
          # y el sufijo se mantiene con "...GatewayFilterFactory" para esta primera alternativa de "filtro por rutas".
          ##- name: Ejemplo
            ##args:
            # Estos 3 son nombres son dados y asingnados por nosotros en este archivo ".yml"
            # Y deben coincidir con los atributos de la clase de configuracion de la clase "EjemploGatewayFilterFactory"
            # Lista de mapas(key-value)
              ##mensaje: Hola mi mensaje personalizado
              ##cookieNombre: usuario
              ##cookieValor: RafaelMinaya
        # Configuracion de la ruta al microservicio "servicio-items" asignada por el API Gateway
        - id: servicio-items
          uri: lb://servicio-items        
          predicates:
          - Path=/api/items/**
          filters:
          - StripPrefix=2
          # Filtros que vienen por defecto. Mas detalles en la documentacion oficial.
          # Filtro que agrega al header del request, un parametro que queramos(name:token-request y value: 123456)
          - AddRequestHeader=token-request, 123456
          # Filtro que agrega al header del response, un parametro que queramos(name:token-response y value: 123456)
          - AddResponseHeader=token-response, 12345678
          # Filtro que modifica el header del response, modificando el tipo del contenido a texto plano
          - SetResponseHeader=Content-Type, text/plain
          # Filtro que agrega un params del request (key:nombre y value: rafael)
          - AddRequestParameter=nombre, rafael